version: '3'

services:

    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www
        networks:
            - app-networks
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        #Entrar de forma interativa
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-networks
        depends_on:
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint.initdb.d
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-networks

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-networks

networks:
    app-networks:
        driver: bridge
